import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      'en_US': {
        'bhajanBank': 'Bhajan Bank',
        'bhajanBankText': 'BHAJAN\nBANK',
        'enterMobileNumber': 'Please Enter Your Mobile Number',
        'mobileError': 'Please enter valid mobile number',
        'selectPhoneCode': 'Select your phone code',
        'search': 'Search...',
        'resendOtp': 'Resend OTP',
        'enterOtp': 'Enter Otp!',
        'phoneVerification': 'PHONE VERIFICATION',
        'getOTPButton': 'GET OTP',
        'enterOTPVerify': 'ENTER OTP TO VERIFY',
        'otpSendMobileNumber': 'OTP has been sent to',
        'changeMobileNumber': 'Change Number ?',
        'registration': 'REGISTRATION',
        'male': 'Male',
        'female': 'Female',
        'readNow': 'READ NOW',
        'confirmation': 'Confirmation',
        'verifyButton': 'VERIFY',
        'refresh': 'Refresh',
        'profile': 'Profile',
        'searchCountry': 'Search country here',
        'searchState': 'Search state here',
        'searchAge' : 'Search age here',
        'searchCity': 'Search city here',
        'submit': 'Submit',
        'surnameError' : 'Please enter surname',
        'nameError' : 'Please enter name',
        'lastNameError' : 'Please enter lastname',
        'dobError' : 'Please select date of birth',
        'plotNoError' : 'Please enter plot no',
        'societyError' : 'Please enter society name',
        'areaError' : 'Please enter area',
        'pincodeError' : 'Please enter pincode',
        'emailError' : 'Please enter email',
        'selectMember' : 'Select member',
        'addMember' : 'Add member',
        'note' : 'Note',
        'yes' : 'Yes',
        'no' : 'No',
        'memberDeleteMsg' : 'Are you sure you want to remove\nthis Member?',
        'memberDeleteMsgDesc' : ' If you remove the niyam\n then all records of this\n niyam will be remove\n permanently.',
        'selectNiyam': 'Select Niyam',
        'yourSelectNiyam' : 'Your Selected Niyams',
        'noDataFound' : 'No data found...',
        'niyamDeleteMsg' : 'Are you sure you want to remove\nthis niyam?',
        'niyamDeleteMsgDesc' : ' If you remove the niyam\n then all records of this\n niyam will be remove\n permanently.',
        'edit' : 'Edit',
        'information' : 'Information',
        'watchNow' : 'Watch Now',
        'save' : 'Save',
        'myDaily' : 'My Daily',
        'target' : 'Target',
        'myAnnual' : 'My Annual',
        'rajatJayantiMahotsav' : 'RAJAT JAYANTI MAHOTSAV \n2024',
        'yourActivity' : 'Your Target',
        'reset' : 'Reset',
        'back' : 'Back',
        'occasionOfFestival' : 'On the occasion of the festival',
        'numberOfLessonRemaining' : 'Number of Lessons Remaining',
        'everyDayAchieveYourGoal' : 'Every day to achieve your goal',
        'readThePledge' : 'Read the Pledge',
        'specialInformation' : 'For Special Information',
        'clickOnInfo' : "Click on (Info).",
        'clickToWatchVideoStunner' : 'Click here to watch the video of the stunner',
        'daily' : 'Daily',
        'monthly' : 'Monthly',
        'yearly' : 'Yearly',
        'earnedTotalCoin' : 'Yoa Earned Total Coin',
        'notification' : 'Notification',
        'rewards' : 'REWARDS',
        'Rewards': 'Rewards',
        'specialRewards' : 'Special Rewards',
        'youEarn' : 'You Earn',
        'topTenUser' : 'Top 10 user',
        'otherBooks' : 'OTHER BOOKS',
        'skip' : 'Skip',
        'next' : 'Next',
        'selectLanguage' : 'Please select language',
        'logoutText' : 'Are you sure you want to logout?',
        'addMalaDesc' : '“ God is always with me \nHence everything is possible “',
        'day' : 'Day',
        'hours' : 'Hours',
        'minute' : 'Minute',
        'second' : 'Second',
        'validEmail' : 'Please enter valid email id',
      },
      'gu_IN': {
        'bhajanBank': 'ભજન બેંક',
        'bhajanBankText': 'ભજન\nબેંક',
        'enterMobileNumber': 'કૃપા કરીને તમારો મોબાઈલ નંબર દાખલ કરો',
        'mobileError': 'કૃપા કરીને માન્ય મોબાઇલ નંબર દાખલ કરો',
        'selectPhoneCode': 'તમારો ફોન કોડ પસંદ કરો',
        'search': 'શોધો...',
        'resendOtp': 'ઓટીપી ફરીથી મોકલો',
        'enterOtp': 'ઓટીપી દાખલ કરો!',
        'phoneVerification': 'ફોન ચકાસણી',
        'getOTPButton': 'ઓટીપી મેળવો',
        'enterOTPVerify': 'ચકાસવા માટે ઓટીપી દાખલ કરો',
        'otpSendMobileNumber': 'પર ઓટીપી મોકલવામાં આવ્યો છે',
        'changeMobileNumber': 'નંબર બદલો?',
        'registration': 'નોંધણી',
        'male': 'પુરુષ',
        'female': 'સ્ત્રી',
        'readNow': 'હમણાં વાંચો',
        'confirmation': 'પુષ્ટિકરણ',
        'verifyButton': 'ચકાસો',
        'refresh': 'તાજું કરો',
        'profile': 'પ્રોફાઇલ',
        'searchCountry': 'દેશ અહીં શોધો',
        'searchState': 'રાજ્ય અહીં શોધો',
        'searchCity': 'શહેર અહીં શોધો',
        'submit': 'સબમિટ કરો',
        'surnameError' : 'કૃપા કરીને અટક દાખલ કરો',
        'nameError' : 'કૃપા કરીને નામ દાખલ કરો',
        'lastNameError' : 'કૃપા કરીને છેલ્લું નામ દાખલ કરો',
        'dobError' : 'કૃપા કરીને જન્મ તારીખ પસંદ કરો',
        'plotNoError' : 'કૃપા કરીને પ્લોટ નં દાખલ કરો',
        'societyError' : 'કૃપા કરીને સોસાયટીનું નામ દાખલ કરો',
        'areaError' : 'કૃપા કરીને વિસ્તાર દાખલ કરો',
        'pincodeError' : 'કૃપા કરીને પિનકોડ દાખલ કરો',
        'emailError' : 'કૃપા કરીને ઇમેઇલ દાખલ કરો',
        'selectMember' : 'સભ્ય પસંદ કરો',
        'addMember' : 'સભ્ય ઉમેરો',
        'note' : 'નોંધ',
        'yes' : 'હા',
        'no' : 'ના',
        'memberDeleteMsg' : 'શું તમે ખરેખર આ સભ્યને દૂર કરવા\nમાંગો છો?',
        'memberDeleteMsgDesc' : ' જો તમે નિયામ\n દૂર કરો છો, તો આ\n નિયમના તમામ રેકોર્ડ્સ કાયમ માટે દૂર કરવામાં આવશે.',
        'selectNiyam': 'નિયમ પસંદ કરો',
        'yourSelectNiyam' : 'તમારા પસંદ કરેલા નિયમ',
        'noDataFound' : 'કોઈ ડેટા મળ્યો નથી...',
        'niyamDeleteMsg' : 'શું તમે ખરેખર આ નિયમ\nદૂર કરવા માંગો છો?',
        'niyamDeleteMsgDesc' : 'જો તમે નિયામ\n દૂર કરો છો, તો આ\n નિયમના તમામ રેકોર્ડ્સ કાયમ માટે દૂર કરવામાં આવશે.',
        'edit' : 'સંપાદિત કરો',
        'information' : 'માહિતી',
        'watchNow' : 'હવે જુઓ',
        'save' : 'સાચવો',
        'myDaily' : 'મારો દૈનિક',
        'target' : 'લક્ષ્ય',
        'myAnnual' : 'મારો વાર્ષિક',
        'rajatJayantiMahotsav' : 'રજત જયંતિ મહોત્સવ \n2024',
        'yourActivity' : 'તમારો ટાર્ગેટ',
        'reset' : 'રીસેટ કરો',
        'back' : 'પાછળ',
        'occasionOfFestival' : 'ઉત્સવ નિમિત્તે',
        'numberOfLessonRemaining' : 'બાકી રહેલા પાઠની સંખ્યા',
        'everyDayAchieveYourGoal' : 'તમારો લક્ષ્ય પ્રાપ્ત કરવા દરરોજ',
        'readThePledge' : 'વચનામૃત વાંચો',
        'specialInformation' : 'વિશેષ માહિતી માટે',
        'clickOnInfo' : ' (Info) પર ક્લિક કરો.',
        'clickToWatchVideoStunner' : 'કંઠસ્થ કરનારના વિડિઓ જોવા અહીં ક્લિક કરો',
        'daily' : 'દૈનિક',
        'monthly' : 'માસિક',
        'yearly' : 'વાર્ષિક',
        'earnedTotalCoin' : 'તમે કુલ સિક્કો મેળવ્યો',
        'notification' : 'સૂચના',
        'rewards' : 'પુરસ્કારો',
        'Rewards' : 'પુરસ્કારો',
        'specialRewards' : 'વિશેષ પુરસ્કારો',
        'youEarn' : 'તમે કમાઓ',
        'topTenUser' : 'ટોચના 10 વપરાશકર્તા',
        'otherBooks' : 'અન્ય પુસ્તકો',
        'searchAge' : 'અહીં ઉંમર શોધો',
        'skip': 'અવગણો',
        'next' : 'આગળ',
        'selectLanguage' : 'કૃપા કરીને ભાષા પસંદ કરો',
        'logoutText' : 'શું તમે ખરેખર લોગઆઉટ કરવા માંગો છો?',
        'addMalaDesc' : '“ ભગવાન હંમેશા મારી સાથે છે \nતેથી બધું શક્ય છે ”',
        'day' : 'દિવસ',
        'hours' : 'કલાક',
        'minute' : 'મિનિટ',
        'second' : 'બીજું',
        'validEmail' : 'કૃપા કરીને માન્ય ઈમેલ આઈડી દાખલ કરો',
      }
    };
  }
}
